[package]
name = "dsr"
version = "0.1.0"
edition = "2024"

[dependencies]
bus = "2.4.1"
log = { version = "0.4.28", features = ["kv"] }
pretty_env_logger = "0.5.0"
rand = "0.9.2"
uuid = { version = "1.18.1", features = ["v4"] }
